<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * TopicCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicCommentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getComments($topicId, $offset = 0, $limit = null)
	{
		$query = $this->createQueryBuilder('c')
			->where('c.topicId = :topicId')
			->setParameter('topicId', $topicId)
			->orderBy('c.createdAt', 'ASC')
			->getQuery();

		$query->setFirstResult($offset);

		if ($limit)
			$query->setMaxResults($limit);

		$paginator = new Paginator($query);

		return $paginator;
	}
}
