<?php

namespace AppBundle\Repository;

/**
 * TopicCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicCommentRepository extends \Doctrine\ORM\EntityRepository
{
	public function getComments($topicId)
	{
		$query = $this->createQueryBuilder('c')
			->where('c.topicId = :topicId')
			->setParameter('topicId', $topicId)
			->orderBy('c.createdAt', 'ASC')
			->getQuery();

		return $query->getResult();
	}
}
